name: CI

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    strategy:
      fail-fast: false
      max-parallel: 3
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.GH_TOKEN }}
    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_MARKDOWN: true
        DEFAULT_BRANCH: develop
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
